### ISSUE TITLE
some requirements are not installled

### ISSUE THREAD

**Issue by Jose2025-12** [DrewThomasson/ebook2audiobook#1348]
install with Git,

after double click ebook2audiobook.cmd, it takes 50mins to download and setup, at the end ,it shows **cmake\rustup\tesseract** is not installed, and **pwsh is not internal/external order, neither a exe program**

<img width="1230" height="978" alt="Image" src="https://github.com/user-attachments/assets/7b2f2a0a-6268-436e-ad3d-037f46028cc0" />

<img width="1230" height="978" alt="Image" src="https://github.com/user-attachments/assets/dc952453-78b2-4b0a-ae1f-9a6f791d4cda" />

Are there anything i can do to solve this problems?

Many, many  thanks in advance for all your kindly help!

**Comment by ROBERT-MCDOWELL** [comment]
I need the full terminal log please

**Comment by ROBERT-MCDOWELL** [comment]
and also provide all requested informations in English about your computer or it will be impossible for me to debug anything

**Comment by ROBERT-MCDOWELL** [comment]
Also please try the last version v25.12.17

**Comment by ROBERT-MCDOWELL** [comment]
should be fixed with v25.12.18. run with powershell rather than batch if it persists.

**Comment by Jose2025-12** [comment]
Sorry for this late reply and thanks you very much  for you kindly help, i am new to git and github.

i tried PowerShell this time, still missing those requirements, showed message like below:

<img width="2382" height="1708" alt="Image" src="https://github.com/user-attachments/assets/20df1560-5c38-4f8d-8a1a-a9a12b8e02d0" />

appreciated for you continous help.

**Comment by ROBERT-MCDOWELL** [comment]
are you running in ebook2audiobook folder:
ebook2audiobook.cmd
or are you double clicking on it?
try to run again in a batch terminal
