### ISSUE TITLE
Installprocess fails on Ubuntu 24.04

### ISSUE THREAD

**Issue by GodGotzi** [DrewThomasson/ebook2audiobook#144]
When running ebook2audiobook.sh I have this error

![image](https://github.com/user-attachments/assets/f977b1c4-5f98-4b21-9b92-db61172634c8)

On the bottom it says: No module named 'unidic'

When i try installing unidic by hand with

`./python_env/bin/python -m pip install unidic`

I get this error

![image](https://github.com/user-attachments/assets/94bc5dda-1a97-48b4-9fbf-6e1c0af12722)

Do you know how to fix this?

**Comment by ROBERT-MCDOWELL** [comment]
could you try 
./python_env/bin/python -m pip install mecab
./python_env/bin/python -m pip install mecab-python3
then
./python_env/bin/python -m pip install unidic

**Comment by GodGotzi** [comment]
fails again with
`... pip install mecab`

![image](https://github.com/user-attachments/assets/1ca8d0f7-d54e-41ad-a221-a0ce490598ad)

**Comment by GodGotzi** [comment]
Got it to work I think

with this
[https://github.com/QuantumWizard888/CaboCha-Ubuntu-18-04-LTS-Installation-Guide](url)

**Comment by ROBERT-MCDOWELL** [comment]
if you read well my comment there was the solution alrady
apt-get install *mecab*

**Comment by danieltomasz** [comment]
macOS also has problem with installing `mecab` via pip, installing it via homebrew helps

**Comment by ROBERT-MCDOWELL** [comment]
some OS needs OS packages to be installed so I fixed them for the next git update.

**Comment by GodGotzi** [comment]
> if you read well my comment there was the solution alrady apt-get install _mecab_

No, this didn't work. After I successfully installed mecab, it gave the same error.

In the guide I installed all the dependencies too and this somehow worked

**Comment by danieltomasz** [comment]
@GodGotzi For me installing mecab externallly and removing  `mecab` from pip dependencies from requirements and  pyproject worked (but still  leaving `mecab-python3`)

**Comment by ROBERT-MCDOWELL** [comment]
@GodGotzi 
apt-get install mecab* (the star means all packages starting with mecab)
or sudo apt install -y mecab libmecab-dev mecab-ipadic
not all OS need to install out of pip these packages, that's why you had this issue. I fixed it for the next git update

**Comment by mahdi155000** [comment]
I have done all the things you mentioned, but my problem still persists. Also, I am on Debian.

**Comment by ROBERT-MCDOWELL** [comment]
I suggest to wait the release 2.1.0 where all pending bugs are (theorically) solved.
