### ISSUE TITLE
bark is not working

### ISSUE THREAD

**Issue by nockiee** [DrewThomasson/ebook2audiobook#849]
**This is just a rudimentary guide, don't be too intimidated, You don't have to follow this to the tee**
**BEFORE TO OPEN AN ISSUE, MAKE SURE THAT IT HASN'T ALREADY BEEN SOLVED OR REPORTED. :)**
**Check it with the issue search field**

**Script Mode**
- Native

**Script Version**
- 25.6.16

**Process Mode**
- Gradio
  
**Operating System:**
 - Windows
 
**Command Line used to start ebook2audiobook**
- powershell

**Describe the bug**
bark is not working. When trying to translate the text in Russian, an error occurs..

**Terminal log**
```
v25.6.16 native mode
C:\ebook2audiobook\python_env\Lib\site-packages\jieba\_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
IPs available for connection:
['26.94.207.240', '192.168.0.155', '169.254.147.158', 'fe80::73f2:f473:af99:f607', '2001:0:284a:364:c8f:a5d2:430c:49c5', 'fe80::c8f:a5d2:430c:49c5', '172.18.208.1', 'fe80::5b14:1af6:252c:ebc3', '127.0.0.1', '::1']
Note: 0.0.0.0 is not the IP to connect. Instead use an IP above to connect.
* Running on local URL:  http://0.0.0.0:7860
* To create a public link, set `share=True` in `launch()`.
Processing eBook file: hellow.txt
Using CPU -
Running command: C:\Users\nockiee\scoop\shims\ebook-convert.EXE C:\ebook2audiobook\tmp\ebook-aabc4911-b0ff-455f-87c0-e36fefe09030\9278aeade0ca5feeb335a13177615b36\hellow.txt C:\ebook2audiobook\tmp\ebook-aabc4911-b0ff-455f-87c0-e36fefe09030\9278aeade0ca5feeb335a13177615b36\__hellow.epub
Conversion options changed from defaults:
  smarten_punctuation: True
  disable_font_rescaling: True
  input_encoding: 'utf-8'
  output_profile: 'generic_eink'
  flow_size: 0
  verbose: 1
  epub_version: '3'
1% Конвертирую входной файл в HTML...
InputFormatPlugin: TXT Input running
on C:\ebook2audiobook\tmp\ebook-aabc4911-b0ff-455f-87c0-e36fefe09030\9278aeade0ca5feeb335a13177615b36\hellow.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'C:\\ebook2audiobook\\tmp\\calibre-594128ru\\vk9h7ndt_plumber\\index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Выполняются изменения в электронной книге…
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Запускается плагин EPUB Output
Splitting markup on page breaks and flow limits, if any...
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
Upgrading to EPUB 3...
EPUB output written to C:\ebook2audiobook\tmp\ebook-aabc4911-b0ff-455f-87c0-e36fefe09030\9278aeade0ca5feeb335a13177615b36\__hellow.epub
Выходные данные сохранены в   C:\ebook2audiobook\tmp\ebook-aabc4911-b0ff-455f-87c0-e36fefe09030\9278aeade0ca5feeb335a13177615b36\__hellow.epub


*******************************************************************************
NOTE:
The warning "Character xx not found in the vocabulary."
MEANS THE MODEL CANNOT INTERPRET THE CHARACTER AND WILL MAYBE GENERATE
(AS WELL AS WRONG PUNCTUATION POSITION) AN HALLUCINATION TO IMPROVE THIS MODEL,
IT NEEDS TO ADD THIS CHARACTER INTO A NEW TRAINING MODEL.
YOU CAN IMPROVE IT OR ASK TO A TRAINING MODEL EXPERT.
*******************************************************************************

C:\ebook2audiobook\lib\classes\tts_engines\coqui.py:66: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  xtts_builtin_speakers_list = torch.load(self.speakers_path)
C:\ebook2audiobook\python_env\Lib\site-packages\torch\nn\utils\weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
```
  WeightNorm.apply(module, name, dim)
conversion 0.00%: 0/1 Block 1 containing 1 sentences...
['Привет, Мир!']
Converting builtin eng voice to rus...
xtts Loaded!
convert() error: bark is None
conversion 0.00%: 0/1
convert_chapters2audio() failed!

**Comment by ROBERT-MCDOWELL** [comment]
this is already fixed in the coming release and last git soon.

**Comment by ROBERT-MCDOWELL** [comment]
could you try 25.6.24 or last git?

**Comment by ROBERT-MCDOWELL** [comment]
should be fixed. thanks to reopen if it persists.

**Comment by DrewThomasson** [comment]
### Nope 

### Bark Issue Still Persists

Mac book pro M1 Pro 16 gb ram

## Version 25.6.24

### Command

`./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK > log.txt 2>&1`

### Error:
```bash
conversion 0.00%: 0/1 
Block 1 containing 1 sentences...
convert() error: bark is None
convert_chapters2audio() failed!
```

### Log: 

[log.txt](https://github.com/user-attachments/files/20884384/log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
did you try 25.6.25?

**Comment by DrewThomasson** [comment]
25.6.24 is the latest number in the file for the latest git pull rn

```bash
drew@MacBookPro ebook2audiobook % git pull
Already up to date.
drew@MacBookPro ebook2audiobook % cat VERSION.txt 
25.6.24%                                                                        drew@MacBookPro ebook2audiobook % 
```

**Comment by ROBERT-MCDOWELL** [comment]
ok I update again. but Bark should work. try to delete all the cache in models/

**Comment by DrewThomasson** [comment]
kk 

I'll also reinstall to be safe :)

**Comment by ROBERT-MCDOWELL** [comment]
cause doing the same command on my local machine in NATVIE gives
INFO:TTS.tts.layers.bark.load_model:model loaded: 302.1M params, 2.079 loss
bark Loaded!
conversion 0.00%: 0/1 Block 1 containing 1 sentences...

**Comment by DrewThomasson** [comment]
kk running test command again

**Comment by DrewThomasson** [comment]
So i should test again on my end now?

(just tell me when to test :) )

**Comment by ROBERT-MCDOWELL** [comment]
you can. last git.

**Comment by DrewThomasson** [comment]
Mac book pro M1 Pro 16 gb ram

```bash
drew@MacBookPro ebook2audiobook % date "+%Y-%m-%d %H:%M:%S"

2025-06-24 09:31:17
drew@MacBookPro ebook2audiobook % git pull
Already up to date.
drew@MacBookPro ebook2audiobook % cat VERSION.txt 
25.6.25%                                                                        drew@MacBookPro ebook2audiobook % 

```

### Command 

`./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK > log.txt 2>&1`


### Error 

```bash
conversion 0.00%: 0/1 
Block 1 containing 1 sentences...
convert() error: bark is None
convert_chapters2audio() failed!
```

### Log

[log.txt](https://github.com/user-attachments/files/20884749/log.txt)

**Comment by DrewThomasson** [comment]
To be fair all I see changed from the git pull was this

```bash
drew@MacBookPro ebook2audiobook % git pull
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8 (delta 1), reused 3 (delta 1), pack-reused 0 (from 0)
Unpacking objects: 100% (8/8), 11.66 KiB | 1.94 MiB/s, done.
From https://github.com/DrewThomasson/ebook2audiobook
   c7152a4..589763c  main           -> origin/main
   e4da391..15ba18f  v25            -> origin/v25
   5f57dd2..dcda198  workflow-patch -> origin/workflow-patch
Updating c7152a4..589763c
Fast-forward
 VERSION.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by DrewThomasson** [comment]
That was after I re-installed `E2A`

hmm

odd that your not getting the issue tho

**Comment by nockiee** [comment]
my log from the latest version also doesn't work unfortunately( https://pastebin.com/4nsYM2tQ

**Comment by ROBERT-MCDOWELL** [comment]
could you try other engines?

**Comment by nockiee** [comment]
https://pastebin.com/59k2v4E1 only bark doesn't work

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks. don't know what's happening. it works on my side and no debug log about it. do you have more than 4GB RAM?
I clone it again and see.

**Comment by ROBERT-MCDOWELL** [comment]
ok cloned again I can reproduce it :-\. I have to search what's happening.

**Comment by ROBERT-MCDOWELL** [comment]
I found it. there is a bug on a condition to install transformers and btw this package was missing.

**Comment by ROBERT-MCDOWELL** [comment]
@DrewThomasson @nockiee 
could you check the version of coqui-tts into python_env env?

**Comment by nockiee** [comment]
> ok thanks. don't know what's happening. it works on my side and no debug log about it. do you have more than 4GB RAM?
> I clone it again and see.

if this information is still useful, 16gb

**Comment by nockiee** [comment]
> @DrewThomasson @nockiee 
> could you check the version of coqui-tts into python_env env?

There's no way right now. I'll try it when I get home.

**Comment by DrewThomasson** [comment]
### coqui-tts
### Version: 0.26.2 

```bash
drew@MacBookPro ebook2audiobook % conda activate /Users/drew/ebook2audiobook/python_env
(/Users/drew/ebook2audiobook/python_env) drew@MacBookPro ebook2audiobook % pip show coqui-tts
Name: coqui-tts
Version: 0.26.2
Summary: Deep learning for Text to Speech.
Home-page: https://github.com/idiap/coqui-ai-TTS
Author: 
Author-email: Eren Gölge <egolge@coqui.ai>
License: MPL-2.0
Location: /Users/drew/ebook2audiobook/python_env/lib/python3.12/site-packages
Requires: anyascii, coqpit-config, coqui-tts-trainer, cython, einops, encodec, fsspec, gruut, inflect, librosa, matplotlib, monotonic-alignment-search, num2words, numpy, packaging, pysbd, pyyaml, scipy, soundfile, torch, torchaudio, tqdm, transformers, typing-extensions
Required-by: 
(/Users/drew/ebook2audiobook/python_env) drew@MacBookPro ebook2audiobook % 

```

**Comment by ROBERT-MCDOWELL** [comment]
and transformers version?

**Comment by DrewThomasson** [comment]
### Transformers

### Version: 4.51.3

```bash
drew@Drews-MacBook-Pro ~ % conda activate /Users/drew/ebook2audiobook/python_env 
(/Users/drew/ebook2audiobook/python_env) drew@Drews-MacBook-Pro ~ % pip show transformers
Name: transformers
Version: 4.51.3
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /Users/drew/ebook2audiobook/python_env/lib/python3.12/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: coqui-tts
```

**Comment by ROBERT-MCDOWELL** [comment]
ok try to update it:

pip install transformers --upgrade

**Comment by DrewThomasson** [comment]
### KK Done its now on Transformers Version: 4.52.4 

```bash
drew@MacBookPro ebook2audiobook % conda activate /Users/drew/ebook2audiobook/python_env
(/Users/drew/ebook2audiobook/python_env) drew@MacBookPro ebook2audiobook % pip install transformers --upgrade
Requirement already satisfied: transformers in ./python_env/lib/python3.12/site-packages (4.51.3)
Collecting transformers
  Downloading transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: filelock in ./python_env/lib/python3.12/site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in ./python_env/lib/python3.12/site-packages (from transformers) (0.33.0)
Requirement already satisfied: numpy>=1.17 in ./python_env/lib/python3.12/site-packages (from transformers) (2.2.6)
Requirement already satisfied: packaging>=20.0 in ./python_env/lib/python3.12/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./python_env/lib/python3.12/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./python_env/lib/python3.12/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in ./python_env/lib/python3.12/site-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in ./python_env/lib/python3.12/site-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in ./python_env/lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in ./python_env/lib/python3.12/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./python_env/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./python_env/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in ./python_env/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: charset_normalizer<4,>=2 in ./python_env/lib/python3.12/site-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./python_env/lib/python3.12/site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./python_env/lib/python3.12/site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./python_env/lib/python3.12/site-packages (from requests->transformers) (2025.6.15)
Downloading transformers-4.52.4-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 50.5 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.51.3
    Uninstalling transformers-4.51.3:
      Successfully uninstalled transformers-4.51.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
coqui-tts 0.26.2 requires transformers<4.52,>=4.47.0, but you have transformers 4.52.4 which is incompatible.
Successfully installed transformers-4.52.4
(/Users/drew/ebook2audiobook/python_env) drew@MacBookPro ebook2audiobook % pip show transformers
Name: transformers
Version: 4.52.4
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /Users/drew/ebook2audiobook/python_env/lib/python3.12/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: coqui-tts

```

**Comment by DrewThomasson** [comment]
Same error 

`./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK > log.txt 2>&1`

### Log 

[log.txt](https://github.com/user-attachments/files/20893785/log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
try to clone your v25 branch. I still didn't merge on main.
also try with CPU rather than GPU just to be sure it does not come from a specific point of code.

**Comment by ROBERT-MCDOWELL** [comment]
that's weird. on my macbook it works, on my jetson not (bark is None), but with the same coqui-tts and transformers version

**Comment by nockiee** [comment]
[log.txt](https://github.com/user-attachments/files/20894519/log.txt)

problem has not been solved :(

**Comment by nockiee** [comment]
if it helps, i use windows 11, 16 gb ram, and i tried it in "default" mode and as an administrator, but i still get the same error

**Comment by ROBERT-MCDOWELL** [comment]
are you using CPU or GPU?

**Comment by ROBERT-MCDOWELL** [comment]
I need also the eb2ab version your are using on windows 11.

**Comment by nockiee** [comment]
![Image](https://github.com/user-attachments/assets/5bd4debd-ac64-4d80-98d9-ef6661f21765)

i selected this thread and download it

**Comment by nockiee** [comment]
25.6.25

**Comment by ROBERT-MCDOWELL** [comment]
could you try the last git on main branch?

**Comment by DrewThomasson** [comment]
### Commands used to run on Macbook M1 pro 16gb ram laptop

```bash
cd ebook2audiobook

date

git branch

git pull

cat VERSION.txt

 conda activate /Users/drew/ebook2audiobook/python_env && pip show coqui-tts && pip show transformers

conda deactivate

./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK > log.txt 2>&1

```

### Commands Output

```bash
drew@MacBookPro ~ % cd ebook2audiobook 
drew@MacBookPro ebook2audiobook % date
Thu Jun 26 11:04:20 EDT 2025
drew@MacBookPro ebook2audiobook % git branch
* main
  v25
drew@MacBookPro ebook2audiobook % git pull
Already up to date.
drew@MacBookPro ebook2audiobook % cat VERSION.txt 
25.6.25%                                                                        drew@MacBookPro ebook2audiobook % conda activate /Users/drew/ebook2audiobook/python_env && pip show coqui-tts && pip show transformers
Name: coqui-tts
Version: 0.26.2
Summary: Deep learning for Text to Speech.
Home-page: https://github.com/idiap/coqui-ai-TTS
Author: 
Author-email: Eren Gölge <egolge@coqui.ai>
License: MPL-2.0
Location: /Users/drew/ebook2audiobook/python_env/lib/python3.12/site-packages
Requires: anyascii, coqpit-config, coqui-tts-trainer, cython, einops, encodec, fsspec, gruut, inflect, librosa, matplotlib, monotonic-alignment-search, num2words, numpy, packaging, pysbd, pyyaml, scipy, soundfile, torch, torchaudio, tqdm, transformers, typing-extensions
Required-by: 
Name: transformers
Version: 4.52.4
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /Users/drew/ebook2audiobook/python_env/lib/python3.12/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: coqui-tts
(/Users/drew/ebook2audiobook/python_env) drew@MacBookPro ebook2audiobook % conda deactivate
drew@MacBookPro ebook2audiobook % ./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK > log.txt 2>&1

```

### Full log of `./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK > log.txt 2>&1`

[log.txt](https://github.com/user-attachments/files/20928728/log.txt)

### Error message

```bash
conversion 0.00%: 0/1 
Block 1 containing 1 sentences...
convert() error: bark is None
convert_chapters2audio() failed!
```

**Comment by DrewThomasson** [comment]
And when I run the bark voice cloning command I get the same error

`./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK --voice "voices/eng/elder/male/DavidAttenborough_24000.wav" > log.txt 2>&1`


### Error 

```bash
conversion 0.00%: 0/1 
Block 1 containing 1 sentences...
convert() error: bark is None
convert_chapters2audio() failed!
```

### Full log

[log.txt](https://github.com/user-attachments/files/20928766/log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
did you try on linux?

**Comment by ROBERT-MCDOWELL** [comment]
torch version?

**Comment by DrewThomasson** [comment]
Name: torch
Version: 2.7.1
Name: transformers
Version: 4.52.4
Name: coqui-tts
Version: 0.26.2

**Comment by pjssilva** [comment]
Just to let you know that I have the same problem on Linux (Ubuntu 25.04) and using ebook2audiobook version  25.6.25. Log is attached.

[log.txt](https://github.com/user-attachments/files/20946132/log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
could you try the last git or v25.6.27?

**Comment by pjssilva** [comment]
Still the same.

[log.txt](https://github.com/user-attachments/files/20949916/log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
ok I targeted the issue. it comes from the fact that coqui-tts 0.26.2 is installing numpy2 which is not compatible with Bark.
try to downgrade (temporarly until the coqui-tts dev will fix it) to 0.26.0, so:
conda activate ./python_env (linux/mac)
conda activate .\python_env (windows)
pip install coqui-tts==0.26.0
conda deactivate

OR

git pull
or v25.6.28

and run in native or recreate the docker

then it should work again.

**Comment by DrewThomasson** [comment]
### WORKS NOW ! :D (tested with Version `v25.6.28` on the `v25` ebook2audiobook branch)


Tested with this command

`./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"`


### OUTPUT

https://github.com/user-attachments/assets/9628c089-d80a-4dfe-9a0b-d5d927d19a7d


Tested with this command

`./ebook2audiobook.sh --headless --ebook "tools/workflow-testing/test1.txt" --tts_engine BARK`


### OUTPUT

https://github.com/user-attachments/assets/8f3420ca-b67f-454a-bc36-4c2b98671ac2

**Comment by ROBERT-MCDOWELL** [comment]
yes, I just tested a commit enighard from coqui-tts fixing the issue from some nump 1 residues in bark layer.
so next coqui-tts version will be ok.

**Comment by DrewThomasson** [comment]
`BARK` Confirmed to also work in docker!!  :D

I tried `docker compose up` on (tested with Version v25.6.28 on the v25 ebook2audiobook branch)

**Comment by ROBERT-MCDOWELL** [comment]
main branch should work too.

**Comment by pjssilva** [comment]
I can confirm that downgrading pip makes it work from the command line on Linux (Ubuntu 25.04).
